name: Python Static Analysis with MyPy
on:
  push:
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Run MyPy
        run: pip3 install mypy && mypy . --exclude='docs/|examples/|setup\.py'
     